version: 2.1

orbs:
  architect: giantswarm/architect@5.4.0

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          name: app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "promxy-app"
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: aws-app-collection
          app_name: "promxy-app"
          app_namespace: "monitoring"
          app_collection_repo: "aws-app-collection"
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
