apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "resource.default.name"  . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      containers:
      - name: {{ include "name" . }}
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.promxy.image.name }}:{{ .Values.promxy.image.tag }}"
        args:
        - "--bind-addr=:{{ .Values.promxy.port }}"
        - "--config={{ .Values.promxy.mountPath }}/config.yaml"
        - "--log-level=debug"
        - "--web.enable-lifecycle"
        - "--web.external-url=/promxy"
        command:
        - "/bin/promxy"
        ports:
        - containerPort: {{ .Values.promxy.port }}
          name: web
          protocol: TCP
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /promxy/-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /promxy/-/ready
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: "{{ .Values.promxy.mountPath }}"
          name: promxy-config
          readOnly: true
      # container to reload configs on configmap change
      - name: promxy-server-configmap-reload
        args:
        - "--volume-dir={{ .Values.promxy.mountPath }}"
        - "--webhook-url=http://localhost:{{ .Values.promxy.port }}/promxy/-/reload"
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.promxy.configmapReloadImage.name }}:{{ .Values.promxy.configmapReloadImage.tag }}"
        resources:
          limits:
            cpu: 25m
            memory: 25Mi
          requests:
            cpu: 25m
            memory: 25Mi
        volumeMounts:
        - mountPath: "{{ .Values.promxy.mountPath }}"
          name: promxy-config
          readOnly: true
      imagePullSecrets:
      - name: {{ include "resource.pullSecret.name" . }}
      volumes:
      - name: promxy-config
        configMap:
          name: {{ include "resource.default.name" . }}
