apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-oauth2-proxy
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    app: {{ include "resource.prometheus.serviceName" . }}
spec:
  rules:
  - host: {{ .Values.Installation.V1.Monitoring.Prometheus.Host }}
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2
  tls:
  - hosts:
    - {{ .Values.Installation.V1.Monitoring.Prometheus.Host }}
    {{- if .Values.Installation.V1.Monitoring.Prometheus.Letsencrypt }}
    secretName: monitoring-prometheus
    {{- else }}
    secretName: prometheus-certs-secret
    {{- end }}
