{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}-basic-auth
  namespace: {{ include "resource.default.namespace" . }}
  annotations:
    {{- if .Values.monitoring.prometheus.letsencrypt }}
    kubernetes.io/tls-acme: "true"
    {{- with .Values.monitoring.prometheus.clusterIssuerName }}
    cert-manager.io/cluster-issuer: "{{ . }}"
    {{- end }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # basic-auth for global Promxy to be able to access all installation-level
    # Promxies
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "resource.default.name" . }}
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{- if .Values.security.restrictAccess.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.security.subnet.vpn }}"
    {{- end }}
    {{- if .Values.ingress.externalDNS }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.monitoring.prometheus.host }}
    giantswarm.io/external-dns: managed
    {{- end }}    
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.monitoring.prometheus.host }}
    http:
      paths:
      - path: /promxy(/|$)(.*)
        pathType: Prefix
        backend:
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          service:
            name: {{ include "resource.default.name" . }}
            port:
              number: {{ .Values.promxy.port }}
{{- else }}
          serviceName: {{ include "resource.default.name" . }}
          servicePort: {{ .Values.promxy.port }}
{{- end }}
  tls:
  - hosts:
    - {{ .Values.monitoring.prometheus.host }}
    secretName: prometheus-tls
