{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}-oauth
  namespace: {{ include "resource.default.namespace" . }}
  annotations:
    {{- if .Values.monitoring.prometheus.letsencrypt }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    # OAuth2 SSO access for humans
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    {{- if .Values.security.restrictAccess.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.security.subnet.vpn }}"
    {{- end }}
    {{- if .Values.ingress.externalDNS }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.monitoring.prometheus.host }}
    giantswarm.io/external-dns: managed
    {{- end }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.monitoring.prometheus.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          service:
            name: {{ include "resource.default.name" . }}
            port:
              number: {{ .Values.promxy.port }}
{{- else }}
          serviceName: {{ include "resource.default.name" . }}
          servicePort: {{ .Values.promxy.port }}
{{- end }}
  tls:
  - hosts:
    - {{ .Values.monitoring.prometheus.host }}
    secretName: prometheus-tls
