apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "resource.default.name" . }}
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.Installation.V1.Monitoring.Prometheus.Host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "resource.default.name" . }}
          servicePort: {{ .Values.promxy.port }}
        path: /promxy
  tls:
  - hosts:
    - {{ .Values.Installation.V1.Monitoring.Prometheus.Host }}
    secretName: prometheus-tls
