apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}-basic-auth
  namespace: {{ include "resource.default.namespace" . }}
  annotations:
    {{- if .Values.monitoring.prometheus.letsencrypt }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # basic-auth for global Promxy to be able to access all installation-level
    # Promxies
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "resource.default.name" . }}
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{- if .Values.security.restrictAccess.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.security.subnet.vpn }}"
    {{- end }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.monitoring.prometheus.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "resource.default.name" . }}
          servicePort: {{ .Values.promxy.port }}
        path: /promxy(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.monitoring.prometheus.host }}
    secretName: prometheus-tls
