apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.Installation.V1.Monitoring.Prometheus.Letsencrypt }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "resource.default.name" . }}
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{- if .Values.Installation.V1.Security.RestrictAccess.Enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.Installation.V1.Security.Subnet.VPN }}"
    {{- end }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.Installation.V1.Monitoring.Prometheus.Host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "resource.default.name" . }}
          servicePort: {{ .Values.promxy.port }}
        path: /
  tls:
  - hosts:
    - {{ .Values.Installation.V1.Monitoring.Prometheus.Host }}
    secretName: prometheus-tls
