Installation:
  V1:
    Registry:
      Domain: quay.io

pod:
  user:
    id: 0
  group:
    id: 1000

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

promxy:
  image:
    name: "giantswarm/promxy"
    tag: "v0.0.62"
  port: 8082

  mountPath: /etc/promxy

  service:
    port: 8082

  configmapReloadImage:
    name: giantswarm/configmap-reload
    tag: v0.3.0

  serverGroups: []
