# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

monitoring:
  prometheus:
    host: ""
    letsencrypt: true
  promxy:
    htpasswd: ""

pod:
  user:
    id: 1000
  group:
    id: 1000

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

promxy:
  image:
    name: "giantswarm/promxy"
    tag: "v0.0.81"
  port: 8082

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi

  mountPath: /etc/promxy

  service:
    port: 8082

  configmapReloadImage:
    name: giantswarm/configmap-reload
    tag: v0.3.0

  configmapReloadResources:
    requests:
      cpu: 25m
      memory: 25Mi
    limits:
      cpu: 25m
      memory: 25Mi

  serverGroups: []

security:
  restrictAccess:
    enabled: false
  subnet:
    vpn: ""

ingress:
  externalDNS: false

registry:
  domain: quay.io

# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  seccompProfile:
    type: RuntimeDefault
