monitoring:
  prometheus:
    host: ""
    letsencrypt: true
  promxy:
    htpasswd: ""

pod:
  user:
    id: 1000
  group:
    id: 1000

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

promxy:
  image:
    name: "giantswarm/promxy"
    tag: "v0.0.75"
  port: 8082

  mountPath: /etc/promxy

  service:
    port: 8082

  configmapReloadImage:
    name: giantswarm/configmap-reload
    tag: v0.3.0

  serverGroups: []

security:
  restrictAccess:
    enabled: false
  subnet:
    vpn: ""

registry:
  domain: quay.io
  pullSecret:
    dockerConfigJSON: "Cg=="
